name: artisanl-cnn-sweep
project: Artisanal CNN
method: bayes
metric:
  name: testing_loss
  goal: minimize

parameters:
  input_size:
    values: [224]
  filter_sizes:
    values: [128, 256, 512]
  learning_rate:
    values: [0.0001, 0.00001, 0.000001]
  activation_function:
    values: [relu]
  optimizer:
    values: [sgd, adam]
  epochs:
    values: [60, 80]
  batch_size:
    values: [32]