name: patnet-hyperparam-sweep
method: grid
project: Elodea PatNet Redux
metric:
  name: testing_loss
  goal: minimize

parameters:
  hidden_sizes:
    values: [256, 512, 1024]
  learning_rate:
    values: [0.0001, 0.00001, 0.000001]
  activation_function:
    values: [relu, leaky_relu]
  dropout:
    values: [0.2, 0.4, 0.6, 0.8]
  optimizer:
    values: [sgd, adam]